### ISSUE TITLE
Error packing new BFLYT Nintendo Switch

### ISSUE THREAD

**Issue by Migushthe2nd** [Tyulis/3DSkit#18]
When trying to repack the `LineFooter.json` -> `LineFooter.bflyt` an error is generated. Unpacking is fine though.
``` python 3DSkit.py -pf BFLYT -o .\LineFooter-edit.bflyt .\LineFooter.json -v
Packing .\LineFooter-edit.bflyt...
Packing BFLYT
Traceback (most recent call last):
  File "3DSkit.py", line 249, in <module>
    result = main(args, opts)
  File "3DSkit.py", line 193, in main
    pack_files(files, args.out, args.compression, args.format, args.big, args.verbose, opts)
  File "3DSkit.py", line 52, in pack_files
    pack.pack(filenames, output, format, endian, verbose, opts)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\__init__.py", line 10, in pack
    return func(*args)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\util\utils.py", line 18, in __new__
    return self.main(*args, **kwargs)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 69, in main
    self.packdata(data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 87, in packdata
    self.packsection(secname, section, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 98, in packsection
    self.packmat1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 265, in packmat1
    self.pack('3f', node['rotation'], node['x warp'], node['y warp'], output)
KeyError: 'x warp'
```
File:
https://drive.google.com/file/d/1n42hjXlsJS0WZGEfnwIjtsZxZtgBdWz7/view?usp=sharing

**Comment by Migushthe2nd** [comment]
Another file `RdtBalloon.json` -> `RdtBalloon.bflyt`:
It does repack though, but the hex is different.

``` python ..\3DSkit.py -pf BFLYT -o "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\blyt-\RdtBalloon.json"-repacked.bflyt "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\blyt-\RdtBalloon.json" -v 
Packing S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\blyt-\RdtBalloon.json-repacked.bflyt...
Packing BFLYT
Traceback (most recent call last):
  File "..\3DSkit.py", line 249, in <module>
    result = main(args, opts)
  File "..\3DSkit.py", line 193, in main
    pack_files(files, args.out, args.compression, args.format, args.big, args.verbose, opts)
  File "..\3DSkit.py", line 52, in pack_files
    pack.pack(filenames, output, format, endian, verbose, opts)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\__init__.py", line 10, in pack
    return func(*args)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\util\utils.py", line 18, in __new__
    return self.main(*args, **kwargs)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 69, in main
    self.packdata(data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 87, in packdata
    self.packsection(secname, section, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 102, in packsection
    self.packpas1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 316, in packpas1
    self.packsection(subsection, data[subsection], output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 108, in packsection
    self.packwnd1(name, data, output)
  File "S:\Mijn Drive\Things\NSW\Themes\Very nice theme\tools\3DSkit-master\pack\BFLYT.py", line 349, in packwnd1
    self.pack('(2f)(2f)(2f)(2f)', node['top left'], node['top right'], node['bottom left'], node['bottom right'], output)
NameError: name 'node' is not defined
```
File:
https://drive.google.com/file/d/1DqmzoZDQDpDbOndvdDnCaZ_6t3gWaCC-/view?usp=sharing

**Comment by Tyulis** [comment]
Poof !
Fixed. I hope there isn't any more problems like that.

BTW, theorically the hex are just shifted because of a strange padding in usd1 sections, but it shouldn't be a problem.

**Comment by Migushthe2nd** [comment]
It's working as expected now
