### ISSUE TITLE
Error extracting .bflyt "KeyError: '__parent'"

### ISSUE THREAD

**Issue by islonely** [Tyulis/3DSkit#23]
Trying to extract a .bflyt to JSON and I'm getting KeyError: '__parent'.

Terminal Output:
PS D:\Switch Modding\romfs\lyt\ResidentMenu\blyt> python C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\3dSkit.py -x RdtBase.bflyt

--------RdtBase.bflyt--------
No compression
BFLYT file found
Extracting...
Traceback (most recent call last):
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\3dSkit.py", line 249, in <module>
    result = main(args, opts)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\3dSkit.py", line 169, in main
    extract_files(filename, args.big, args.format, args.verbose, opts)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\3dSkit.py", line 112, in extract_files
    unpack.extract(filename, file, format, endian, verbose, opts)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\unpack\__init__.py", line 16, in extract
    unpacker = cls(*args)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\util\utils.py", line 18, in __new__
    return self.main(*args, **kwargs)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\unpack\BFLYT.py", line 66, in main
    self.readdata(data)
  File "C:\Users\imado\Downloads\3DSkit-master\3DSkit-master\unpack\BFLYT.py", line 107, in readdata
    self.curparent = self.curparent['__parent']
KeyError: '__parent'
PS D:\Switch Modding\romfs\lyt\ResidentMenu\blyt>

**Comment by islonely** [comment]
Just got an error complaining about a "parent" being null in a different program, so I think it might be my file not your program.
